### ISSUE TITLE
Fortune leaderboard 

### ISSUE THREAD

**Issue by flappyprince** [Talia-Team/Talia#28]
Add a leaderboard which takes into account the amount of coins users have invested, worth of inventory and coins. As opposed to only coins as this doesn't give a good picture of what users actually could have if they liquidated all their valuables.
called with !lb fortune

**Comment by falconnine9** [comment]
This would probably be impossible to add due to the way data is stored.
I mean, it would be possible to do but super unoptimized and way too slow.

So I won't be adding it (maybe one day i'll come up with an idea for it)

**Comment by flappyprince** [comment]
If you ignore the value of the items in users inventories (which i also see the problem of attaining effieciently, because of the way it is stored in the DB), it is rather easy to add together the amount invested with the balance.

This is the reason i opened the issue up again
